package controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;
import util.ActionStage;
import util.AlertScreen;

import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.ResourceBundle;

import dataAccess.Driver;
import javafx.event.ActionEvent;

import javafx.scene.control.PasswordField;

public class LoginSceneController implements Initializable{
	@FXML
	private TextField text_url;
	@FXML
	private TextField text_user;
	@FXML
	private PasswordField text_password;
	@FXML
	private Button btn_connect;

	public static String DB_url;
	public static String DB_user;
	public static String DB_password;
	
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		
				
	}

	// Event Listener on Button[#btn_connect].onAction
	@FXML
	public void event_connectToDB(ActionEvent event) {
		// TODO Autogenerated
		DB_url = text_url.getText();
		DB_user = text_user.getText();
		DB_password = text_password.getText();
			try {
				Connection con = DriverManager.getConnection(DB_url, DB_user,DB_password);
				Driver.setConnectionForAllTables(DB_url, DB_user, DB_password);
				Boolean connect = AlertScreen.getMessageScreen("Welcome", "DB connection successful");
				if(connect) {
					FXMLLoader loader = new ActionStage(new Stage(), "/view/MainScene.fxml", "Digital CookBook", 735, 555)
							.getLoader();
					Stage stage = (Stage) text_url.getScene().getWindow();
					stage.close();
				}
				
			} catch (SQLException e) {
				AlertScreen.getMessageScreen("Error", "DB Connection Unsuccessful, Please type again!");
				text_url.setText(null);
				text_user.setText(null);
				text_password.setText(null);
		}
	}
}
